name: porfirevich-dev

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    image: porfirevich:dev
    environment:
      NODE_ENV: development
      TYPEORM_SYNCHRONIZE: "true"
    restart: on-failure:5

  db:
    extends:
      file: docker-compose.yml
      service: db
    restart: "no"

volumes:
  db18:
