name: porfirevich-dev

services:
  app:
    extends:
      file: docker-compose.yml
      service: app
    image: porfirevich:dev
    environment:
      NODE_ENV: development
    restart: on-failure:5

  db:
    extends:
      file: docker-compose.yml
      service: db
    image: postgres:17-alpine
    restart: "no"

volumes:
  db:
